[package]
name = "aoc_2023"
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
common = { path = "../common" }

anyhow.workspace = true
regex.workspace = true
